// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ArtistSearchController from "./artist_search_controller"
application.register("artist-search", ArtistSearchController)

import GenreSearchController from "./genre_search_controller"
application.register("genre-search", GenreSearchController)

import MaintainMessagesController from "./maintain_messages_controller"
application.register("maintain-messages", MaintainMessagesController)

import MaintainRoomsController from "./maintain_rooms_controller"
application.register("maintain-rooms", MaintainRoomsController)

import SliderController from "./slider_controller"
application.register("slider", SliderController)

import TagSearchController from "./tag_search_controller"
application.register("tag-search", TagSearchController)
