services:
  vincula:
    build: .
    user: tempUser  
    networks:
      - shared-network     
    volumes:
      - sqlite_data:/app/db

volumes:
  sqlite_data:

networks:
  shared-network:
    external: true    